---

- name: destroy AWS resources
  hosts: localhost
  connection: local
  vars_files:
    - ../group_vars/all
  tasks:
    - name: gather instance facts
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance.group-name: "{{ group_name }}"
      register: facts

    - name: destroy instances
      ec2:
        region: "{{ ec2_region }}"
        instance_id: "{{ item.instance_id }}"
        state: absent
        wait: true
      with_items: "{{ facts.instances }}"

    - name: gather ebs facts
      ec2_vol_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:Name": "{{ workshop_name }}"
      register: ebs_facts

    - name: destroy ebs
      ec2_vol:
        region: "{{ ec2_region }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ ebs_facts.volumes }}"

    - name: destroy keypair
      ec2_key:
        name: "{{ workshop_name }}"
        region: "{{ ec2_region }}"
        state: absent
      register: key

    - debug:
        msg: "Delete the VPC manually through the AWS Console"
