---
# This role installs miniconda + qiime2 core distribution

- name: check if miniconda3 dir exists
  stat:
    path: "{{ miniconda_path }}"
  register: miniconda

- name: download miniconda
  become: true
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /usr/local/src/miniconda.sh
    mode: u+rx
  when: not miniconda.stat.exists

- name: install miniconda
  become: true
  command: "/usr/local/src/miniconda.sh -b -p {{ miniconda_path }}"
  when: not miniconda.stat.exists

- name: make dirs
  become: true
  file:
    state: directory
    path: "{{ item }}"
    owner: ubuntu
    group: ubuntu
    recurse: yes
  with_items:
    - "{{ miniconda_path }}"
    - "{{ miniconda_path }}/../tmp"
  when: not miniconda.stat.exists

- name: check if qiime2 env exists
  stat:
    path: "{{ miniconda_path }}/envs/qiime2-{{ qiime2_release }}/bin/qiime"
  register: env

- name: upgrade conda
  environment:
    PATH: "{{ miniconda_path }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  command: "{{ item }}"
  with_items:
    - conda update conda -q -y

- name: download env file
  become: true
  get_url:
    url: https://data.qiime2.org/distro/core/qiime2-{{ qiime2_release }}-py35-linux-conda.yml
    dest: /etc/env.yml
  when: not env.stat.exists

- name: install qiime2
  environment:
    PATH: "{{ miniconda_path }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    TMPDIR: "{{ miniconda_path }}/../tmp"
  shell: "conda env create -n qiime2-{{ qiime2_release }} --file /etc/env.yml"
  args:
    executable: /bin/bash
  when: not env.stat.exists

- name: activate qiime2 env (conda magic, don't touch)
  environment:
    PATH: "{{ miniconda_path }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  shell: source activate qiime2-{{ qiime2_release }}
  args:
    executable: /bin/bash
