---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: install dependencies
      apt:
        name:
          - acl
          - bzip2
          - git
          - make
          - python3-psycopg2
          - tar
          - virtualenv
        update_cache: yes
    - name: copy qiime2 tools
      synchronize:
        src: files/tools
        dest: /opt/qiime2_tools
    - name: set up ephemeris virtualenv
      pip:
        name: ephemeris
        virtualenv: /opt/venv
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
  post_tasks:
    # here we just install a single tool, galaxy should handle the rest for us
    - name: install tools via ephemeris
      shell: |
        /opt/venv/bin/install_tool_deps \
          -a {{ vault_api_key }} \
          -i qiime2_tools_import \
          -g {{ inventory_hostname }}

- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: create gie dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ galaxy_user.name }}"
        group: "{{ galaxy_user.name }}"
      loop:
        - "{{ interactive_environments_plugins_path }}"
        - "{{ interactive_environments_proxy_path }}"
    - name: Include Interactive Environments package installation tasks
      include_tasks:
        file: roles/galaxyproject.interactive_environments/tasks/install_dependencies.yml
        apply:
          become: true
          become_user: root
  roles:
    - role: galaxyproject.interactive_environments
      become: true
      become_user: "{{ galaxy_user.name }}"
