---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: install dependencies
      apt:
        name:
          - acl
          - bzip2
          - git
          - make
          - python3-psycopg2
          - tar
          - virtualenv
        update_cache: yes
    - name: copy qiime2 tools
      synchronize:
        src: files/tools
        dest: /opt/qiime2_tools
    - name: set up ephemeris
      pip:
        name: ephemeris
        virtualenv: /opt/venv
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
  post_tasks:
    # here we just install a single tool, galaxy should handle the rest for us
    - name: install tools via ephemeris
      shell: "/opt/venv/bin/install_tool_deps -a {{ vault_api_key }} -t /opt/qiime2_tools/tools/suite_qiime2_alignment/qiime2_alignment_mafft-add.xml -g https://{{ inventory_hostname }}"
