---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: update apt sources
      raw: apt update
    - name: install dependencies
      package:
        name:
          - acl
          - bzip2
          - git
          - make
          - python3-psycopg2
          - tar
          - virtualenv
    - name: copy qiime2 tools
      synchronize:
        src: files/tools
        dest: /opt/qiime2_tools
  roles:
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - galaxyproject.nginx
