galaxyservers:
  hosts:
    workshop-server.qiime2.org:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/projects/qiime2/caporaso-lab-secrets/keys/ec2/galaxy-testdrive/galaxy-testing.pem
