---
# This role sets up all workshop machines with common dependencies

- name: update all packages to the latest version
  apt:
    upgrade: dist

- name: grab required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - tree
    - zsh

- name: create groups
  group:
    name: "{{ hostvars[item]['grp'] }}"
    state: present
  with_items: "{{ groups['compute_hosts'] }}"

- name: set up ssh (general)
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^PasswordAuthentication.*$', line: 'PasswordAuthentication yes' }
    - { regexp: '^.*Port.*$', line: 'Port 22' }
    - { regexp: '^.*MaxStartups.*$', line: 'MaxStartups 200' }

- name: restart ssh
  service:
    name: ssh
    state: restarted
