---
# This role sets up all workshop machines with common dependencies

- name: grab required packages
  apt:
    state: present
    name:
      - unzip
      - tree
      - zsh

- name: update all packages to the latest version
  apt:
    upgrade: dist

- name: reboot
  reboot:

- name: create groups
  group:
    name: "{{ hostvars[item]['grp'] }}"
    state: present
  with_items: "{{ groups['compute_hosts'] }}"
