---

- name: destroy AWS resources
  hosts: localhost
  connection: local
  vars_files:
    - ../group_vars/all
  tasks:
    - name: gather instance facts
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance.group-name: "{{ group_name }}"
      register: facts

    - name: destroy instances
      ec2:
        region: "{{ ec2_region }}"
        instance_id: "{{ item.instance_id }}"
        state: absent
        wait: true
      with_items: "{{ facts.instances }}"

    - name: gather ebs facts
      ec2_vol_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:Name": "{{ workshop_name }}"
      register: ebs_facts

    - name: destroy ebs
      ec2_vol:
        region: "{{ ec2_region }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ ebs_facts.volumes }}"

    - name: destroy keypair
      ec2_key:
        name: "{{ workshop_name }}"
        region: "{{ ec2_region }}"
        state: absent
      register: key

    - name: gather vpc facts
      ec2_vpc_net_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:Name": "{{ workshop_name }}"
      register: vpc

    - name: early exit
      meta: end_play
      when: vpc.vpcs|length == 0

      #     - name: destroy vpc subnet
      #       ec2_vpc_subnet:
      #         region: "{{ ec2_region }}"
      #         vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
      #         cidr: "{{ vpc_cidr_block }}"
      #         state: absent
      #       register: subnets
      # 
      #     - debug:
      #         var: subnets
      # 
      #     - name: gather nacl facts
      #       ec2_vpc_nacl_info:
      #         region: "{{ ec2_region }}"
      #         filters:
      #           vpc-id: "{{ vpc.vpcs[0].vpc_id }}"
      #       register: nacl
      # 
      #     - debug:
      #         var: nacl
      # 
      #     - name: destroy nacl
      #       ec2_vpc_nacl:
      #         region: "{{ ec2_region }}"
      #         nacl_id: "{{ nacl.nacls[0].nacl_id }}"
      #         vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
      #         state: absent
      # 
      #     - name: gather security group facts
      #       ec2_group_info:
      #         region: "{{ ec2_region }}"
      #         filters:
      #           vpc-id: "{{ vpc.vpcs[0].vpc_id }}"
      #       register: sg
      # 
      #     - debug:
      #         var: sg
      # 
      #     - debug:
      #         var: vpc
      # 
      #     - name: destroy security groups
      #       ec2_group:
      #         region: "{{ ec2_region }}"
      #         group_id: "{{ item.group_id }}"
      #         state: absent
      #       with_items: "{{ sg.security_groups }}"
      # 
      #     - name: gather igw facts
      #       ec2_vpc_igw_info:
      #         region: "{{ ec2_region }}"
      #         filters:
      #           "attachment.vpc-id": "{{ vpc.vpcs[0].vpc_id }}"
      #       register: igw
      # 
      #     - debug:
      #         var: igw
      # 
      #     - name: destroy igw
      #       ec2_vpc_igw:
      #         region: "{{ ec2_region }}"
      #         state: absent
      #         vpc_id: "{{ vpc.vpcs[0].vpc_id }}"

    - name: destroy vpc
      ec2_vpc_net:
        region: "{{ ec2_region }}"
        cidr_block: "{{ vpc_cidr_block }}"
        purge_cidrs: yes
        name: "{{ workshop_name }}"
        state: absent
